# Permalinks
permalink:           pretty

# Setup
title:               nmangla
tagline:             Data Science Blog
url:                 http://nmangla.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              nmangla
  url:               https://www.linkedin.com/in/nikhil-mangla-87b54035/
  email:             nmangla1@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/nmangla

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
